import { ActiveItem } from "./types";

function DecodeResultInfo({ activeItem }: { activeItem?: ActiveItem }) {
  const text = {
    amount: "The value of a proof, denominated in whatever the tokens unit is",
    secret:
      "The secret generated by the token holder. It is revealed once the token is redeemed.",
    signature:
      "The unblinded signature of the mint. Proofs that this token was indeed created by the mint",
    id: "The ID of the keyset used to sign this token",
  };
  if (!activeItem) {
    return (
      <div className="flex flex-col items-center bg-slate-700 justify-center text-center">
        <p>Select item to see details</p>
      </div>
    );
  }
  return (
    <div className="flex flex-col items-center bg-slate-700 justify-center text-center p-4">
      <p>{activeItem.type.toUpperCase()}</p>
      <p className="text-sm">{text[activeItem.type]}</p>
    </div>
  );
}

export default DecodeResultInfo;
